### ISSUE TITLE
Some concerning stuff

### ISSUE THREAD

**Issue by Rnen** [iRebbok/IDisconnectDrop#1]
Might wanna create a single dictionary, storing a struct containing both data values instead.
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/IDisconnectDrop.cs#L23-L24

List<Item>.Tolist?
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/DelailCommand.cs#L40

LINQ  .First() also takes a predicate
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/DelailCommand.cs#L36

Naming convention crimes are off the charts
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/DelailCommand.cs#L45

.ToList() for a KeyValuePair foreach? What??
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/DelailCommand.cs#L55
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/EventHandlers.cs#L78

Will recommend putting the entire thing into a dict.TryGetValue instead, as you only have the access the dict once.
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/DelailCommand.cs#L37

MyDict.Keys.Count
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/EventHandlers.cs#L76

This is the **third** time you do GetPlayers in Update
Might wanna do it **once**, and store them in a array.
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/EventHandlers.cs#L105

Foreach(string key in IDisconnectDrop.pVector.Keys)
https://github.com/iRebbok/IDisconnectDrop/blob/07dd745b32fee90d2f3a0c20345e7619f3349e8a/IDisconnectDrop/ListCommand.cs#L37

**Comment by iRebbok** [comment]
Everything will be fixed and converted according to your recommendations. Will also use coroutine to prevent delays.
